### ISSUE TITLE
Programm Stoppt nach zwei "Runden"

### ISSUE THREAD

**Issue by Pils10** [brusayannick/tuv-termin-suche#3]
Euer Script hängt sich bei mir leider immer bei der dritten Durchführung auf. Es sendet die Telegram-Nachricht, wie geplant, nur bei der ersten Runde. Die zweite wird "normal" durchgeführt und bei der dritten Stützt das Script mit folgender Fehlermeldung ab. Ich hoffe, ihr könnt mir helfen.

Traceback (most recent call last):
  File "D:\Systemordner\Python\Scripts\Tuv-Pruefung.py", line 77, in <module>
    main()
  File "D:\Systemordner\Python\Scripts\Tuv-Pruefung.py", line 64, in main
    cntvor1 = termin("Euskirchen")
  File "D:\Systemordner\Python\Scripts\Tuv-Pruefung.py", line 40, in termin
    vor = driver.find_element_by_xpath("//div[@class='ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all']//a[@title='<zurück']")
  File "D:\Systemordner\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\Systemordner\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Systemordner\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Systemordner\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all']//a[@title='<zurück']"}
  (Session info: chrome=93.0.4577.82)

**Comment by Pils10** [comment]
Fixed by adding:

    option.add_argument('incognito')

War scheinbar ein Fehler mit dem Cashing von Chrome. Am besten fügt ihr dies auch in eurem Commit hinzu.

MFG,
Pils10

**Comment by brusayannick** [comment]
Alles klar. Vielen Dank!
